### ISSUE TITLE
#Task 1.2.3: Specify Non-functional Requirements

### ISSUE THREAD

**Issue by faithlimzx** [hxijxe/ict-inf2001-p3-6#6]
Specifying Non-Functional Requirement

Task Title ID: 1.2.3

Task Description: The goal of is to brainstorm and define non-functional requirements (NFRs) to ensure that the Workload Management System after consultation with client. NFRs are important for specifying system's behavior and characteristics. 

Task Goals: To clearly define non-functional requirements to ensure that the Workload Management System meets the desired performance, usability, scalability, reliability, integration, accountability, and error logging standards. 

Success and Completion Criteria: The task will be considered successful when all functional requirements are included as required by the client. The document will be consistently reviewed and approved by the project team and the client. Next phase of the project will start once the client review and approves the non-functional requirements that the project team has specified. 

Allocated Time: 3 days

Start Date & End Date of the Task: 11/09/2023-13/09/2023

Owner of the Task: Angie 

Status of the Task: As of current, still reviewing with client 

Priority of Task: High

**Comment by user963087** [comment]
Work Done Description: The work involved defining the non-functional requirements from the Workload Management System. covering important aspects such as scalability, reliability, integration, accountability, and error logging

Work committed to repo: Not applicable to this task

Impact on Completion Deadline: Contribute positively to the completion of the project by ensuring non-functional requirements are clearly defined and will be met after reviewed and approved by the client and the project team. This task may extend the timeline, due to constant reviewing by the client and the project team, but the impact is minimal. 

Changes to success or Completion Criteria of the Task: No changes to success or completion criteria

Start Date and End Date of Work Done: 13/09/2023-15/09/2023

**Comment by user963087** [comment]
-
